feat: print 42 as an ascii art
alisterd51/gratOS pull request #7
Opened 2024-03-26 22:42 UTC by JonathanDUFOUR

2024-03-27 00:38 UTC, alisterd51 requested changes

2024-03-27 02:37 UTC, JonathanDUFOUR commented on src/ascii_art.rs
> +    use crate::vga_buffer::{Color, Color::*, Writer};
Because I need it in this function specifically, not in the entire global scope.

2024-03-27 02:38 UTC, JonathanDUFOUR commented on src/ascii_art.rs
> +    writer.new_line();
No, I can't, because how we deal with colors forces me to make multiple calls to `Writer::write_byte`, with a call to `Writer::set_background_color` before each. The other option would be to improve the `Writer::write_str` method to be able to interpret the escape sequences like `\x1B[40m`, `\x1B[47m`, `\x1B[0m`, etc...

2024-03-27 02:41 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> -struct ColorCode(u8);
I needed to change it into a primitive integer type because I needed to compute arithmetic operations on the ColorCode type below, and casting a structure into an `u8` wasn't possible directly, even if the structure is wrapping an `u8` as it was.

2024-03-27 02:43 UTC, alisterd51 commented on src/ascii_art.rs
> +    writer.new_line();
I agree that you implement sequences such as `\x1B[40m`

2024-03-27 02:44 UTC, alisterd51 commented on src/ascii_art.rs
> +    use crate::vga_buffer::{Color, Color::*, Writer};
ok

2024-03-27 02:48 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    pub fn new_line(&mut self) {
No, it's not, because of your choice to use mutexes to prevent print fuzzing when we would deal with multiple threads later. Indeed, the `println!` macro locks the `WRITER` before using it. Repeatedly calling it printing each line of the ASCII art one by one would allow other threads to print some mess between two of these lines. That's why the `ascii_art::print_42` function locks the `Writer` once at the beginning, and releases it when the entire print is done. But that's also why I must use the inner methods of the `Writer` instead of the helper macros.

2024-03-27 02:50 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    const DEFAULT_FOREGROUND_COLOR: Color = Color::LightGray;
Yes, but for now, it's not, and thus, it's defined as compile-time constants

2024-03-27 02:51 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +        self.clear_row(BUFFER_HEIGHT - 1);
Alright, I will do.

2024-03-27 02:51 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            self.clear_row(row);
Alright, I will do.

2024-03-27 02:51 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    fn clear_row(&mut self, row: usize) {
Alright, I will do.

2024-03-27 02:54 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +        self.color_code = self.color_code & 0x0F | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4;
Not exactly, look carefully: the first one is setting the background color to a specific one given in parameters, while the second one is here to reset the background color to its default value (did you read the doc comment above the method?)

2024-03-27 02:57 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4,
What would you suggest then? The two above methods don't return any value, and that would be irrelevant to do so. Therefore, this is the simplest way to initialize the `color_code` field.

2024-03-27 03:01 UTC, JonathanDUFOUR commented on src/ascii_art.rs
> +    writer.new_line();
Alright, I will do.

2024-03-27 03:08 UTC, alisterd51 commented on src/vga_buffer.rs
> +    pub fn new_line(&mut self) {
indeed, I assumed that this comment was taken into account: https://github.com/alisterd51/gratOS/pull/7#discussion_r1540265520

2024-03-27 03:11 UTC, alisterd51 commented on src/vga_buffer.rs
> +    const DEFAULT_FOREGROUND_COLOR: Color = Color::LightGray;
in this case please add comment like `// TODO: remove this ASAP because ...`

2024-03-27 03:18 UTC, alisterd51 commented on src/vga_buffer.rs
> +        self.color_code = self.color_code & 0x0F | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4;
no, I'm talking about the logic `color_code = x << 4 | y`
this can be replaced by `color_code = ColorCode::new(x, y)`

2024-03-27 03:24 UTC, alisterd51 commented on src/vga_buffer.rs
> -struct ColorCode(u8);
this is no longer true if the https://github.com/alisterd51/gratOS/pull/7#discussion_r1540284985 and https://github.com/alisterd51/gratOS/pull/7#discussion_r1540285281 comments are applied.

2024-03-27 03:37 UTC, alisterd51 commented on src/vga_buffer.rs
> +            | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4,
like
```rust
color_code: ColorCode::new(Writer::DEFAULT_FOREGROUND_COLOR, Writer::DEFAULT_BACKGROUND_COLOR),
```

2024-03-27 03:42 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    const DEFAULT_FOREGROUND_COLOR: Color = Color::LightGray;
Alright, I will do.

2024-03-27 03:54 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +        self.color_code = self.color_code & 0x0F | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4;
For the two above methods, it's not about setting both the foreground and the background color as you suggest in your example. The arithmetic operation that I do has two steps:
1. preserving the current foreground color while erasing the current background color (`self.color & 0x0F`)
2.  applying the new background color to the result of the previous step (` | (color as u8) << 4`)

So, knowing what this function is expected to do, re-initializing `self.color_code` via a function is very irrelevant because it would need that we match the current foreground color to pass it in parameters to this supposed function. And doing so will require to apply a bitmask anyway (` & 0x0F`).

2024-03-27 03:57 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    pub fn new_line(&mut self) {
But if the escape sequences are well interpreted by the `Writer::write_str` method, then I should be able to use the helper macro, and only once.

2024-03-27 04:00 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4,
We cannot implement methods for a primitive type, I already tried it. But if you prefer, I may create a dedicated function like:
```rust
fn new_color_code(foreground: Color, background: Color) -> ColorCode;
```

2024-03-27 04:05 UTC, alisterd51 commented on src/ascii_art.rs
> +    writer.new_line();
this conversation can only be resolved by a change in the code, I'm reopening it

2024-03-27 04:05 UTC, alisterd51 commented on src/vga_buffer.rs
> +    const DEFAULT_FOREGROUND_COLOR: Color = Color::LightGray;
this conversation can only be resolved by a change in the code, I'm reopening it

2024-03-27 04:05 UTC, alisterd51 commented on src/vga_buffer.rs
> +    fn clear_row(&mut self, row: usize) {
this conversation can only be resolved by a change in the code, I'm reopening it

2024-03-27 04:09 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> -struct ColorCode(u8);
Arithmetic operations, more precisely bitwise operations, will still be required if we want to have a way to change only the foreground color of the background color of a `Writer` instance. The only other option to do so without any bitwise operation is to store both the foreground and background colors in two separate fields in the `Writer` structure. This way, we would be able to change the implementation of the `Writer::set_background_color` method into something like this:
```rust
pub fn set_background_color(&mut self, new_background_color: Color) {
    self.background_color = new_background_color;
    self.color_code = new_color_code(self.foreground_color, self.background_color);
}
```

2024-03-27 04:12 UTC, alisterd51 commented on src/vga_buffer.rs
> +        self.color_code = self.color_code & 0x0F | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4;
in this case, please add 2 methods to `Color Code` such as `update_background()` and `update_foreground()`

2024-03-27 04:15 UTC, alisterd51 commented on src/vga_buffer.rs
> +            | (Writer::DEFAULT_BACKGROUND_COLOR as u8) << 4,
I know, that's why I created the `ColorCode` struct.
put it back in place.

2024-03-27 04:17 UTC, alisterd51 commented on src/vga_buffer.rs
> +        self.clear_row(BUFFER_HEIGHT - 1);
this conversation can only be resolved by a change in the code, I'm reopening it

2024-03-27 04:18 UTC, alisterd51 commented on src/vga_buffer.rs
> +            self.clear_row(row);
this conversation can only be resolved by a change in the code, I'm reopening it

2024-03-29 08:32 UTC, alisterd51 requested changes

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +            0x0A => self.new_line(),
this reduces the understanding of the code. please prefer representation as `b'\n'` when relevant.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +            ascii_character: 0x20,
this reduces the understanding of the code. please prefer representation as `b' '` when relevant.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +                0x0A => self.new_line(),
this reduces the understanding of the code. please prefer representation as `b'\n'` when relevant.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +    #[allow(clippy::single_match)]
why not follow clippy's recommendation?

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +        let mut parameters: [u8; MAXIMUM_LENGTH] = [0; MAXIMUM_LENGTH];
`: [u8; MAXIMUM_LENGTH]` is optional, the compiler has enough context, please remove it.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +            _ => panic!("unknown SRG parameters"),
panicking a kernel for an error that has no impact is a bad idea.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +                panic!("CSI sequence too long");
panicking a kernel for an error that has no impact is a bad idea.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +            panic!("escape sequence ended unexpectedly");
panicking a kernel for an error that has no impact is a bad idea.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +                _ => panic!("unknown escape sequence"),
panicking a kernel for an error that has no impact is a bad idea.

2024-03-29 08:32 UTC, alisterd51 commented on src/vga_buffer.rs
> +    // REMIND: incorrect name, should be `clear_row`
open a issue regarding this point.

2024-03-29 19:05 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            0x0A => self.new_line(),
I voluntarily made this change, because you used the hexadecimal representation instead of the `b<char>` one in the `match` for the range of ASCII printable characters in the `Writer::write_string` method. And having several different representations for the same thing in the codebase is disgusting in my opinion. So I decided to change every other representation of an ASCII character to the hexadecimal one. Moreover, this allows us to represent every 1-byte character the same way, even those not part of the ASCII printable characters.
If you fear that it reduces the understanding of the code, we may put a comment above to say that this is a newline, a space, an opening bracket, etc...

2024-03-29 19:05 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            ascii_character: 0x20,
https://github.com/alisterd51/gratOS/pull/7#discussion_r1544793253

2024-03-29 19:05 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +                0x0A => self.new_line(),
https://github.com/alisterd51/gratOS/pull/7#discussion_r1544793253

2024-03-29 19:22 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    #[allow(clippy::single_match)]
Because using a `match` instead of an `if` is more relevant given a future improvement of the number of CSI sequences that our kernel would be able to interpret. For now, it interprets only the sequences terminated by a `0x6D`(`m`). They define an SGR action (stands for Select Graphic Rendition). But later, we may add more, like sequences terminated by a `0x41`(`A`), a `0x41` (`B`), a `0x43`(`C`), or a `0x44`(`D`), which move the cursor n cells up, down, forward, or backward.
See [here](https://en.wikipedia.org/wiki/ANSI_escape_code#CSIsection) for more existing CSI sequences that we may add in the future.

2024-03-29 19:41 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            _ => panic!("unknown SRG parameters"),
I disagree for the following reasons:
- only the kernel itself will be able to use the `Writer::write_string` method, and thus, we, the developers of it, are the only responsible persons for each call to it.
- it is a usage error, and because of the previous reason, we don't want to develop a kernel with such errors in it. So we want to be informed about it as soon as possible, and panicking is a radical way to ensure that.

2024-03-29 19:42 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +                panic!("CSI sequence too long");
https://github.com/alisterd51/gratOS/pull/7#discussion_r1544813078

2024-03-29 19:42 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +            panic!("escape sequence ended unexpectedly");
https://github.com/alisterd51/gratOS/pull/7#discussion_r1544813078

2024-03-29 19:42 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +                _ => panic!("unknown escape sequence"),
https://github.com/alisterd51/gratOS/pull/7#discussion_r1544813078

2024-03-29 19:45 UTC, JonathanDUFOUR commented on src/vga_buffer.rs
> +    // REMIND: incorrect name, should be `clear_row`
I'll do a merge request for that. But in the meantime, putting a TodoTree comment to not forget it directly in the code is not irrelevant (as a comment has no impact on the program behavior).

2024-04-02 21:02 UTC, alisterd51 requested changes
this MR contains 2 features:
- added interpretation of escape sequences
- creation of an ascii art of 42

so please separate into 2 commits.

(the second depends on the first, and must therefore be located after in the git history)

please also rebase so that the merge commit is not present in the git history

please also respect the 50/72 rule:
- no more than 50 characters for the title
- no more than 72 characters per line for the description

https://www.gitkraken.com/learn/git/best-practices/git-commit-message#git-commit-message-structure

2024-04-04 17:05 UTC, JonathanDUFOUR commented
Alright for the rule that you mentioned. However, this is not what GitKraken says. It says that 72 characters long is the maximum for the title, while the description has no character limit. I assume that the 50/72 rule you mentioned is the one suggested by most developers, but here again, it says that the description should be no longer than 72 characters, not per line.

2024-04-08 12:02 UTC, alisterd51 commented on src/vga_buffer.rs
> +            _ => panic!("unknown SRG parameters"),
There are 2 cases in which a kernel must panic:
- `Explicit Invocation`:
   if the kernel detects a case that is impossible to resolve (for example not enough ram or missing CPU instructions)
- `Implicit Invocation`:
   if a feature is not implemented.

Therefore, either a `panic!()` in the case of an `Explicit Invocation` or a `todo!()` in the case of an `Implicit Invocation`.
No other cases will be tolerated.
The present case is not part of one of these cases and is therefore not tolerated.

2024-04-12 12:00 UTC, closed without merging