build: halt for qemu & reboot created
alisterd51/gratOS pull request #91
Opened 2024-07-23 13:36 UTC by hboissel

both commands added to a module commands. Could be relevant to move print kernel stack there as well.
The reboot command jump to the label created in the initial assembly.
The halt command send a shutdown to qemu so works only on qemu since shutdown is a power management action, it is specific to the hardware.

2024-07-23 16:09 UTC, alisterd51 commented
This addition is a feature: the merge commit and the name of the MR should start with `feat:` instead of `build:`.

2024-07-24 11:46 UTC, hboissel commented
![Screenshot from 2024-07-24 13-45-56](https://github.com/user-attachments/assets/fda45aac-b4fa-4f9f-80dd-dfa3757eac97)

2024-08-29 15:08 UTC, alisterd51 requested changes

2024-08-29 20:51 UTC, hboissel commented on src/commands/print_gdt.rs
> +fn parse_segment_descriptor(descriptor: u64) -> SegmentDescriptor {
![image](https://github.com/user-attachments/assets/0f232741-5f26-42ef-901e-b82a3170dc7d)

2024-09-16 16:16 UTC, alisterd51 commented
can you update the readme regarding the whole GDT part?

2024-10-02 17:24 UTC, alisterd51 requested changes

2024-10-02 17:24 UTC, alisterd51 commented on README.md
> +      - [x] halt
These features are not yet implemented. They will have to be added after the basic shell merge.

2024-10-02 17:24 UTC, alisterd51 commented on src/commands/print_gdt.rs
> +    let mut gdt: [u16; 2] = [0; 2];
```rust
    let mut gdt = [0u16; 2];
```

2024-10-08 09:11 UTC, merged